### ISSUE TITLE
Integrate flyway with Drone CI does't work because of flyway user

### ISSUE THREAD

**Issue by felipeabezerra** [flyway/flyway-docker#100]
Hello everybody,

I am trying to integrate my Drone CI pipeline with flywayDB image and got stuck with this approach below:

On my drone step, I am setting like this:
```
  migrate-forno:
    image: flyway/flyway
    pull: true
    privileged: true
    commands:
      - eval $(cat ./jdbc_creds)
      - export FLYWAY_USER=$$FLYWAY_USERNAME
      - configFiles=/resources/db/config/flyway.conf -locations=filesystem:/resources/db/scripts -connectRetries=2 migrate
    when:
      event: push
      branch: forno
```

As soon as it completes, I receive this error message: 
![image](https://user-images.githubusercontent.com/7806114/186920320-48138995-1996-4599-ab49-cf8994893599.png)

Researching about, I founded that Drone doesn’t work well with images using another user than root.
This topic is disccussed on Drone [forum](https://discourse.drone.io/t/solved-netrc-permission-denied/171).

And I realized that flyway images uses a flyway user like [here](https://github.com/flyway/flyway-docker/blob/34b9876e6d6f3e61d9d0276c3a262f5be938911e/Dockerfile#L6)

Is there any workaround here?

Thanks,
Felipe Bezerra
