### ISSUE TITLE
Flyway did not do variable substitution when used with docker-compose.

### ISSUE THREAD

**Issue by krlsdu** [flyway/flyway-docker#11]
To reproduce the issue try this docker-compose

```
version: '3'
services:
  flyway:
    image: boxfuse/flyway:5.2.4
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=$MYSQL_ROOT_PASSWORD -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

```

the result expected

- Connection with database ok and executed the sql migrations

the  result was

```
SQL State  : 28000
Error Code : 1045
Message    : Access denied for user 'root'@'172.29.0.3' (using password: NO)
```

**Comment by axelfontaine** [comment]
I am afraid this is a Docker Compose and not a Flyway issue as they determine the substitution order.

**Comment by jakkn** [comment]
_Posting a solution should anyone else find their way here._

Variable subsitution in compose can be a little tricky. We must differ between environment variables in the shell in which `docker-compose` is run, and the environment variables defined in the compose yaml file.

Environment variables in the shell are available to `docker-compose` when it runs and parses the yaml file. Default values can be specified in the `.env` file.

Environment variables defined in sections `environment:` and `env_file:` of the compose yaml file are passed to the container and will not be defined in the shell.

Additionally, you can prevent Compose from interpolating a value with double-dollar sign. `$$` is useful in the `entrypoint:` and `command:` sections of the yaml file where you wish to reference environment variables that you don’t want processed by Compose, eg. any variables not defined in the shell. (See https://docs.docker.com/compose/compose-file/#variable-substitution).

This feature makes @krlsdu's example work by adding an extra dollar-sign: `-password=$$MYSQL_ROOT_PASSWORD`.

Unfortunately this does not take you all the way, as the image entrypoint defines no shell around the `flyway` binary that would dereference the environment variables. This results in the string `$MYSQL_ROOT_PASSWORD` being passed in as the password, and is also demonstrated well when specifying schemas with `-schemas=$$MYSQL_DATABASE -password=P@ssw0rd` as this results in a database named `$MYSQL_DATABASE`

![foo](https://user-images.githubusercontent.com/3417835/64817432-21d0cf00-d5aa-11e9-8be5-9f47b9f78743.jpg)
I tried with a couple other options too as you can see in the image.

We can check the image entrypoint with
```
$ docker inspect flyway/flyway | ack -i entrypoint -A2
            "Entrypoint": [
                "/flyway/flyway"
            ],
```

So, to make it work you have to wrap the flyway command in a shell that will dereference the environment variables. Example:

```yml
version: '3'
services:
  flyway:
    image: flyway/flyway
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=myschema
    entrypoint: /bin/bash
    command: [
      "-c",
      "/flyway/flyway -url=jdbc:mysql://db -schemas=$$MYSQL_DATABASE -user=root -password=$$MYSQL_ROOT_PASSWORD -connectRetries=60 migrate"
    ]
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
```

**Comment by MENGKONGSEAN** [comment]
@jakkn 
I also got this error too. 
I follow your explain now it work.
But I case I need env out side of compose.
Example
```
version: '3'
services:
  flyway:
    image: flyway/flyway
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD:-123}
      - MYSQL_DATABASE=${DBNAME:-123}
    entrypoint: /bin/bash
    command: [
      "-c",
      "/flyway/flyway -url=jdbc:mysql://db -schemas=$$MYSQL_DATABASE -user=root -password=$$MYSQL_ROOT_PASSWORD -connectRetries=60 migrate"
    ]
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
```

I use command like this 
`export DBNAME=db`
`export PASSWORD=root`
`sudo docker-compose up -d`
But I can't not get db and root value in compose.
so how to get that value in compose.
