### ISSUE TITLE
 RSA public key is not available client side (option serverRsaPublicKeyFile not set)

### ISSUE THREAD

**Issue by JohnnysMartins** [flyway/flyway-docker#117]
I tried to follow the Official documentation example to run a docker-compose version having a MySQL and flyway image running the migration but an error about RSA public key is been showed

docker-compose.yml example:
```yml

version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306:3306

```
error:
![image](https://user-images.githubusercontent.com/18020633/218497447-1b7cf338-688a-45b1-9b45-945d441b4397.png)
