### ISSUE TITLE
cant use in kubernetes

### ISSUE THREAD

**Issue by ilanni2460** [flyway/flyway-docker#14]
```yaml
apiVersion: v1
kind: List
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: dbflyway-1
    namespace: dev6
  spec:
    parallelism: 1
    completions: null
    backoffLimit: 5
    activeDeadlineSeconds: 1000
    ttlSecondsAfterFinished: 10
    template:
      spec:
        initContainers:
        - name: git-sync
          image: gcr.azk8s.cn/google-containers/git-sync:v3.1.2
          securityContext:
            runAsUser: 65533
          volumeMounts:
          - name: git-source
            mountPath: /tmp/git
          - name: git-secret
            mountPath: /etc/git-secret
          env:
          - name: GIT_SYNC_REPO
            value: "git@gitlab.ilanni.com:devops/dbflyway.git"
          - name: GIT_SYNC_SSH
            value: "true"
          - name: GIT_SYNC_PERMISSIONS
            value: "0777"
          - name: GIT_SYNC_ONE_TIME
            value: "true"
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_DEST
            value: conf
        containers:
        - name: flyway
          image: boxfuse/flyway:5.2.4
          args: ["-configFiles=/flyway/conf/conf/dev6.conf","migrate"]
          volumeMounts:
          - name: git-source
            mountPath: /flyway/
        securityContext:
          fsGroup: 65533
        restartPolicy: Never
        volumes:
        - name: git-source
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-creds
            defaultMode: 288
```
