### ISSUE TITLE
Arm based images

### ISSUE THREAD

**Issue by pixie79** [flyway/flyway-docker#37]
Hi,

I would be good if you could also build arm64 based images which is becoming more common across the Kube/Docker estate by default.

We tend to test our work on mini Raspberry Pi clusters and ideally being able to run this would be great.

Thanks

**Comment by DoodleBobBuffPants** [comment]
Hi. We will likely wait until Docker Hub supports this as part of their automated builds without requiring us to copy qemu in

You could use the Dockerfile to build your own arm64 images for now

**Comment by pixie79** [comment]
Docker Hub does support this now, I currently build my other images based off of the small ubuntu but then all i do it

```
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          tags: "xxx:latest,xxx:${{ github.sha }}"
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Github # default: 8398a7@action-slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
```

The use of Github actions makes it very easy.
