### ISSUE TITLE
ARM64 with docker compose no logs

### ISSUE THREAD

**Issue by edrichhans** [flyway/flyway-docker#89]
Hi! I'm trying to use the image on docker-compose on an M1 mac, and I am getting no logs. Here's my compose file:

```
version: '2.1'

services:
  postgres-test:
    image: postgres
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "test"]
      interval: 5s
      timeout: 1s
      retries: 2
  flyway:
    image: flyway/flyway:latest
    platform: linux/arm64
    container_name: flyway-container
    environment:
      - FLYWAY_USER=test
      - FLYWAY_PASSWORD=test
      - FLYWAY_SCHEMAS=public
      - FLYWAY_URL=jdbc:postgresql://postgres:54320/test
    command: -locations="filesystem:/flyway/sql" -baselineOnMigrate=true -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres-test:
        condition: service_healthy
```

I've tried using flags `-user=test` on the command, setting the platform to `linux/arm64/v8`, removing the platform, all to no avail. 

Docker: v20.10.16, build aa7e414
Mac OS: M1 11.3
