### ISSUE TITLE
Will Jenkins evaluate the exit code of the flyway command?

### ISSUE THREAD

**Issue by straurob** [flyway/flyway-docker#9]
I configured my `docker-compose.yml` according to the example [in the readme](https://github.com/flyway/flyway-docker/blob/master/README.md) and it works fine.

My current setup is that a Docker stack will be deployed based on the `docker-compose.yml`. This deployment is triggered by a `Jenkinsfile`.

Will the Jenkins build fail if the migration fails? Or will Jenkins not be able to pick up the result of the `migrate` command?

```
version: '3'
services:
  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
```
